#!/usr/bin/env bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -euo pipefail

if [[ $# != 6 ]]; then
    printf 'Usage: %s <config-file> <fuseki-base> <dataset> <port> <index-directory> <vector-dimension>\n' "$0" >&2
    exit 1
fi

CONFIG_FILE="$1"
FUSEKI_BASE_DIR="$2"
DATASET="$3"
PORT="$4"
INDEX_DIR="$5"
VECTOR_DIMENSION="$6"

[[ "$DATASET" =~ ^[A-Za-z0-9_-]+$ ]] || { printf 'Invalid dataset name: %s\n' "$DATASET" >&2; exit 1; }
[[ "$PORT" =~ ^[1-9][0-9]*$ && "$PORT" -le 65535 ]] || { printf 'Invalid port: %s\n' "$PORT" >&2; exit 1; }
[[ "$VECTOR_DIMENSION" =~ ^[1-9][0-9]*$ ]] || { printf 'Invalid vector dimension: %s\n' "$VECTOR_DIMENSION" >&2; exit 1; }

mkdir -p "$(dirname "$CONFIG_FILE")" "$FUSEKI_BASE_DIR/extra" "$FUSEKI_BASE_DIR/databases" "$INDEX_DIR/text" "$INDEX_DIR/vector"

escape_turtle_literal() {
    local value="$1"
    value="${value//\\/\\\\}"
    value="${value//\"/\\\"}"
    printf '%s' "$value"
}

text_index="$(escape_turtle_literal "$INDEX_DIR/text")"
vector_index="$(escape_turtle_literal "$INDEX_DIR/vector")"
database_directory="$(escape_turtle_literal "$FUSEKI_BASE_DIR/databases/$DATASET")"

provider_config=''
index_terminator='.'
if [[ -n "${GRAPHRAG_EMBEDDING_API_URL:-}" && -n "${GRAPHRAG_EMBEDDING_API_KEY:-}" && -n "${GRAPHRAG_EMBEDDING_MODEL:-}" && -n "${OPENAI_API_URL:-}" && -n "${OPENAI_API_KEY:-}" && -n "${GRAPHRAG_CHAT_MODEL:-}" ]]; then
    embedding_model="$(escape_turtle_literal "$GRAPHRAG_EMBEDDING_MODEL")"
    chat_model="$(escape_turtle_literal "$GRAPHRAG_CHAT_MODEL")"
    index_terminator=';'
    provider_config=$(cat <<EOF
    grag:embeddingProvider :embeddingProvider ;
    grag:chatProvider :chatProvider .

:embeddingProvider rdf:type grag:HttpEmbeddingProvider ;
    grag:allowExternalCalls true ;
    grag:endpointEnv "GRAPHRAG_EMBEDDING_API_URL" ;
    grag:apiKeyEnv "GRAPHRAG_EMBEDDING_API_KEY" ;
    grag:modelName "$embedding_model" ;
    grag:timeoutSeconds 60 .

:chatProvider rdf:type grag:HttpChatCompletionProvider ;
    grag:allowExternalCalls true ;
    grag:endpointEnv "OPENAI_API_URL" ;
    grag:apiKeyEnv "OPENAI_API_KEY" ;
    grag:modelName "$chat_model" ;
    grag:timeoutSeconds 60 .
EOF
)
fi

system_prompt_config=''
if [[ -n "${GRAPHRAG_SYSTEM_PROMPT:-}" ]]; then
    system_prompt_config='    grag:systemPromptEnv "GRAPHRAG_SYSTEM_PROMPT" ;'
fi

cat > "$CONFIG_FILE" <<EOF
# Generated by graphrag-tutorial-fuseki-config.sh. Do not edit.
# Dataset: $DATASET; port: $PORT; Fuseki base: $FUSEKI_BASE_DIR
@prefix :       <#> .
@prefix fuseki: <http://jena.apache.org/fuseki#> .
@prefix grag:   <https://jena.apache.org/graphrag/vocab#> .
@prefix ja:     <http://jena.hpl.hp.com/2005/11/Assembler#> .
@prefix rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix tdb2:   <http://jena.apache.org/2016/tdb#> .

[] rdf:type fuseki:Server ;
   fuseki:pingEP true ;
   fuseki:statsEP true ;
   fuseki:services ( :service ) .

:service rdf:type fuseki:Service ;
    fuseki:name "$DATASET" ;
    fuseki:endpoint [ fuseki:name "sparql" ; fuseki:operation fuseki:query ] ;
    fuseki:endpoint [ fuseki:name "update" ; fuseki:operation fuseki:update ] ;
    fuseki:endpoint [ fuseki:name "data" ; fuseki:operation fuseki:gsp-rw ] ;
    fuseki:dataset :dataset ;
${system_prompt_config}
    grag:enableGraphRAG true ;
    grag:graphragIndex :index .

# The dataset starts empty. The tutorial uploads the Turtle through the
# Graph Store endpoint after Fuseki has responded to /$/ping.
:dataset rdf:type tdb2:DatasetTDB2 ;
    tdb2:location "$database_directory" .

:index rdf:type grag:GraphRAGIndex ;
    grag:textIndexDir "$text_index" ;
    grag:vectorIndexDir "$vector_index" ;
    grag:vectorDimension $VECTOR_DIMENSION $index_terminator
$provider_config
EOF
